#!/bin/bash
# 贪吃蛇游戏部署脚本 - GitHub Pages

echo "=== 贪吃蛇游戏部署到 GitHub Pages ==="
echo ""
echo "步骤 1: 在 GitHub 创建新仓库"
echo "  - 访问: https://github.com/new"
echo "  - 仓库名: snake-game"
echo "  - 设置为 Public"
echo "  - 不要初始化 README"
echo ""
echo "步骤 2: 推送代码到 GitHub"
echo "  运行以下命令:"
echo ""
echo "  cd /home/ljw/.openclaw/workspace/snake-game"
echo "  git remote add origin https://github.com/YOUR_USERNAME/snake-game.git"
echo "  git push -u origin master"
echo ""
echo "步骤 3: 启用 GitHub Pages"
echo "  - 访问仓库 Settings > Pages"
echo "  - Source: Deploy from a branch"
echo "  - Branch: master, / (root)"
echo "  - Save"
echo ""
echo "步骤 4: 访问游戏"
echo "  游戏地址: https://YOUR_USERNAME.github.io/snake-game/"
echo ""
